#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BeakonMvvm.Droid.Resource", IsApplication=true)]

namespace BeakonMvvm.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::BeakonMvvm.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::BeakonMvvm.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::BeakonMvvm.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::BeakonMvvm.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::BeakonMvvm.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::BeakonMvvm.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::BeakonMvvm.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::BeakonMvvm.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::BeakonMvvm.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::BeakonMvvm.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::BeakonMvvm.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::BeakonMvvm.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::BeakonMvvm.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::BeakonMvvm.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::BeakonMvvm.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::BeakonMvvm.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::BeakonMvvm.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::BeakonMvvm.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::BeakonMvvm.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::BeakonMvvm.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::BeakonMvvm.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::BeakonMvvm.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::BeakonMvvm.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Beakon_Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int BeakonLogo_Large = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int male = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int NotificationIcon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int RemoveContactButton = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int request = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int RequestIcon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int SettingsIcon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int splash = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int sty = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int style_input = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050023
			public const int FavourateContactsLinearLayout = 2131034147;
			
			// aapt resource value: 0x7f050000
			public const int MvvmCrossTagId = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MvxBindingTagUnique = 2131034113;
			
			// aapt resource value: 0x7f05000c
			public const int btnNotification = 2131034124;
			
			// aapt resource value: 0x7f050008
			public const int btnNotificationMain = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int btnNotificationSettings = 2131034116;
			
			// aapt resource value: 0x7f05000b
			public const int btnRequest = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int btnRequestMain = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int btnRequestSettings = 2131034115;
			
			// aapt resource value: 0x7f05000d
			public const int btnSettings = 2131034125;
			
			// aapt resource value: 0x7f050009
			public const int btnSettingsMain = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int btnSettingsSettings = 2131034117;
			
			// aapt resource value: 0x7f050012
			public const int cancelButton = 2131034130;
			
			// aapt resource value: 0x7f05000f
			public const int checkBox1 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int edtName = 2131034128;
			
			// aapt resource value: 0x7f050026
			public const int imageButton1 = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int imageButton2 = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int imageButton3 = 2131034152;
			
			// aapt resource value: 0x7f050006
			public const int imageView1 = 2131034118;
			
			// aapt resource value: 0x7f050015
			public const int linearLayout1 = 2131034133;
			
			// aapt resource value: 0x7f050019
			public const int linearLayout2 = 2131034137;
			
			// aapt resource value: 0x7f05001c
			public const int linearLayout3 = 2131034140;
			
			// aapt resource value: 0x7f050013
			public const int linearLayout4 = 2131034131;
			
			// aapt resource value: 0x7f050002
			public const int linearLayout6 = 2131034114;
			
			// aapt resource value: 0x7f05000a
			public const int listView = 2131034122;
			
			// aapt resource value: 0x7f050011
			public const int sendButton = 2131034129;
			
			// aapt resource value: 0x7f050017
			public const int space1 = 2131034135;
			
			// aapt resource value: 0x7f050014
			public const int space2 = 2131034132;
			
			// aapt resource value: 0x7f05001e
			public const int space3 = 2131034142;
			
			// aapt resource value: 0x7f050021
			public const int switch1 = 2131034145;
			
			// aapt resource value: 0x7f050020
			public const int textAutoCal = 2131034144;
			
			// aapt resource value: 0x7f050022
			public const int textAutoLoc = 2131034146;
			
			// aapt resource value: 0x7f05001d
			public const int textEmail = 2131034141;
			
			// aapt resource value: 0x7f05001f
			public const int textEmailInput = 2131034143;
			
			// aapt resource value: 0x7f050016
			public const int textFirstName = 2131034134;
			
			// aapt resource value: 0x7f050018
			public const int textFirstNameInput = 2131034136;
			
			// aapt resource value: 0x7f05001a
			public const int textLastName = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int textLastNameInput = 2131034139;
			
			// aapt resource value: 0x7f05000e
			public const int textView1 = 2131034126;
			
			// aapt resource value: 0x7f050024
			public const int textView2 = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int toolbar1 = 2131034149;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int answers = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FirstView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int listView_answers = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ListView_Contacts = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int listView_row = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int members = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int navigation = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Notification = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int NotificationCustomListView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int requests = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int settings = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int SplashScreen = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Template = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040009
			public const int SettingsAllContacts = 2130968585;
			
			// aapt resource value: 0x7f040006
			public const int SettingsCalendarAuto = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int SettingsEmail = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int SettingsFavCont = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int SettingsFirstName = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int SettingsLastName = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int SettingsLocationAuto = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int SettingsYourContacts = 2130968584;
			
			// aapt resource value: 0x7f04000a
			public const int abc = 2130968586;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
